;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="Action.Crouch",DevComment="")
GameplayTagList=(Tag="StealthTags.Events.Player.Primary",DevComment="")
GameplayTagList=(Tag="StealthTags.StateTree.Detect",DevComment="")
GameplayTagList=(Tag="StealthTags.StateTree.LostTarget",DevComment="")
GameplayTagList=(Tag="StealthTags.Status.Dead",DevComment="")
GameplayTagList=(Tag="StealthTags.StealthAbilities.Death",DevComment="")
GameplayTagList=(Tag="StealthTags.StealthAbilities.Enemy.HitReact",DevComment="")

