;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="Action.Crouch",DevComment="")
GameplayTagList=(Tag="StealthTags.Events.Enemy.MeleeTraceHit",DevComment="")
GameplayTagList=(Tag="StealthTags.Events.Player.Death",DevComment="")
GameplayTagList=(Tag="StealthTags.Events.Player.HitReact",DevComment="")
GameplayTagList=(Tag="StealthTags.Events.Player.Primary",DevComment="")
GameplayTagList=(Tag="StealthTags.SetByCaller.Projectile",DevComment="")
GameplayTagList=(Tag="StealthTags.StateTree.Detect",DevComment="")
GameplayTagList=(Tag="StealthTags.StateTree.Events.Enemy.AttackEnded",DevComment="")
GameplayTagList=(Tag="StealthTags.StateTree.LostTarget",DevComment="")
GameplayTagList=(Tag="StealthTags.Status.Dead",DevComment="")
GameplayTagList=(Tag="StealthTags.StealthAbilities.Death",DevComment="")
GameplayTagList=(Tag="StealthTags.StealthAbilities.Enemy.Attack",DevComment="")
GameplayTagList=(Tag="StealthTags.StealthAbilities.Enemy.HitReact",DevComment="")

