;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagRedirects=(OldTagName="StealthTags.SetByCaller.Projectile",NewTagName="StealthTags.SetByCaller.Damage")
GameplayTagList=(Tag="Action.Crouch",DevComment="")
GameplayTagList=(Tag="StealthTags.Events.Enemy.MeleeTraceHit",DevComment="")
GameplayTagList=(Tag="StealthTags.Events.Player.Death",DevComment="")
GameplayTagList=(Tag="StealthTags.Events.Player.HitReact",DevComment="")
GameplayTagList=(Tag="StealthTags.Events.Player.Primary",DevComment="")
GameplayTagList=(Tag="StealthTags.Events.Player.Secondary",DevComment="")
GameplayTagList=(Tag="StealthTags.SetByCaller.Damage",DevComment="")
GameplayTagList=(Tag="StealthTags.SetByCaller.MaxDetection",DevComment="")
GameplayTagList=(Tag="StealthTags.StateTree.Detect",DevComment="")
GameplayTagList=(Tag="StealthTags.StateTree.Events.Enemy.AttackEnded",DevComment="")
GameplayTagList=(Tag="StealthTags.StateTree.LostTarget",DevComment="")
GameplayTagList=(Tag="StealthTags.Status.Dead",DevComment="")
GameplayTagList=(Tag="StealthTags.Status.Enemy.Alerted",DevComment="")
GameplayTagList=(Tag="StealthTags.Status.Enemy.Detecting",DevComment="")
GameplayTagList=(Tag="StealthTags.Status.InCombat",DevComment="")
GameplayTagList=(Tag="StealthTags.Status.NotSuppressing",DevComment="")
GameplayTagList=(Tag="StealthTags.Status.SuppressingBreath",DevComment="")
GameplayTagList=(Tag="StealthTags.StealthAbilities.Death",DevComment="")
GameplayTagList=(Tag="StealthTags.StealthAbilities.Enemy.Attack",DevComment="")
GameplayTagList=(Tag="StealthTags.StealthAbilities.Enemy.HitReact",DevComment="")
GameplayTagList=(Tag="StealthTags.StealthAbilities.Player.Suppress",DevComment="")
GameplayTagList=(Tag="StealthTags.StealthAbilities.Player.Takedown",DevComment="")

